//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17929.
// 
#pragma warning disable 1591

namespace BiosWebMailWindows.refServiceWebMailWin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceWebMailSoap", Namespace="http://WebMailWS/")]
    public partial class ServiceWebMail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarCarpetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCarpetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCarpetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInboxFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCarpetaSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarpetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarEmailLeidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoverEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAlumnoByCiOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback NuevoAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NuevoDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLoginUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAlumnosSinMovimientosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDocentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAlumnosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAlumnosXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarStatusAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarDocenteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceWebMail() {
            this.Url = global::BiosWebMailWindows.Properties.Settings.Default.BiosWebMailWindows_refServiceWebMailWin_ServiceWebMail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarCarpetaCompletedEventHandler AgregarCarpetaCompleted;
        
        /// <remarks/>
        public event ListarCarpetasCompletedEventHandler ListarCarpetasCompleted;
        
        /// <remarks/>
        public event EliminarCarpetaCompletedEventHandler EliminarCarpetaCompleted;
        
        /// <remarks/>
        public event getInboxFolderCompletedEventHandler getInboxFolderCompleted;
        
        /// <remarks/>
        public event IsCarpetaSistemaCompletedEventHandler IsCarpetaSistemaCompleted;
        
        /// <remarks/>
        public event GetCarpetaCompletedEventHandler GetCarpetaCompleted;
        
        /// <remarks/>
        public event AgregarEmailCompletedEventHandler AgregarEmailCompleted;
        
        /// <remarks/>
        public event ListarEmailCompletedEventHandler ListarEmailCompleted;
        
        /// <remarks/>
        public event GetEmailCompletedEventHandler GetEmailCompleted;
        
        /// <remarks/>
        public event EliminarEmailCompletedEventHandler EliminarEmailCompleted;
        
        /// <remarks/>
        public event MarcarEmailLeidoCompletedEventHandler MarcarEmailLeidoCompleted;
        
        /// <remarks/>
        public event MoverEmailCompletedEventHandler MoverEmailCompleted;
        
        /// <remarks/>
        public event getAlumnoCompletedEventHandler getAlumnoCompleted;
        
        /// <remarks/>
        public event getAlumnoByCiCompletedEventHandler getAlumnoByCiCompleted;
        
        /// <remarks/>
        public event getDocenteCompletedEventHandler getDocenteCompleted;
        
        /// <remarks/>
        public event NuevoAlumnoCompletedEventHandler NuevoAlumnoCompleted;
        
        /// <remarks/>
        public event NuevoDocenteCompletedEventHandler NuevoDocenteCompleted;
        
        /// <remarks/>
        public event getLoginUsuarioCompletedEventHandler getLoginUsuarioCompleted;
        
        /// <remarks/>
        public event ListarAlumnosSinMovimientosCompletedEventHandler ListarAlumnosSinMovimientosCompleted;
        
        /// <remarks/>
        public event ListarDocentesCompletedEventHandler ListarDocentesCompleted;
        
        /// <remarks/>
        public event ListarAlumnosCompletedEventHandler ListarAlumnosCompleted;
        
        /// <remarks/>
        public event ListarAlumnosXmlCompletedEventHandler ListarAlumnosXmlCompleted;
        
        /// <remarks/>
        public event ActualizarStatusAlumnoCompletedEventHandler ActualizarStatusAlumnoCompleted;
        
        /// <remarks/>
        public event ModificarAlumnoCompletedEventHandler ModificarAlumnoCompleted;
        
        /// <remarks/>
        public event ModificarDocenteCompletedEventHandler ModificarDocenteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/AgregarCarpeta", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarCarpeta(Carpeta c) {
            this.Invoke("AgregarCarpeta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void AgregarCarpetaAsync(Carpeta c) {
            this.AgregarCarpetaAsync(c, null);
        }
        
        /// <remarks/>
        public void AgregarCarpetaAsync(Carpeta c, object userState) {
            if ((this.AgregarCarpetaOperationCompleted == null)) {
                this.AgregarCarpetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCarpetaOperationCompleted);
            }
            this.InvokeAsync("AgregarCarpeta", new object[] {
                        c}, this.AgregarCarpetaOperationCompleted, userState);
        }
        
        private void OnAgregarCarpetaOperationCompleted(object arg) {
            if ((this.AgregarCarpetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCarpetaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarCarpetas", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carpeta[] ListarCarpetas(Alumno a) {
            object[] results = this.Invoke("ListarCarpetas", new object[] {
                        a});
            return ((Carpeta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCarpetasAsync(Alumno a) {
            this.ListarCarpetasAsync(a, null);
        }
        
        /// <remarks/>
        public void ListarCarpetasAsync(Alumno a, object userState) {
            if ((this.ListarCarpetasOperationCompleted == null)) {
                this.ListarCarpetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCarpetasOperationCompleted);
            }
            this.InvokeAsync("ListarCarpetas", new object[] {
                        a}, this.ListarCarpetasOperationCompleted, userState);
        }
        
        private void OnListarCarpetasOperationCompleted(object arg) {
            if ((this.ListarCarpetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCarpetasCompleted(this, new ListarCarpetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/EliminarCarpeta", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarCarpeta(Carpeta c) {
            this.Invoke("EliminarCarpeta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void EliminarCarpetaAsync(Carpeta c) {
            this.EliminarCarpetaAsync(c, null);
        }
        
        /// <remarks/>
        public void EliminarCarpetaAsync(Carpeta c, object userState) {
            if ((this.EliminarCarpetaOperationCompleted == null)) {
                this.EliminarCarpetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCarpetaOperationCompleted);
            }
            this.InvokeAsync("EliminarCarpeta", new object[] {
                        c}, this.EliminarCarpetaOperationCompleted, userState);
        }
        
        private void OnEliminarCarpetaOperationCompleted(object arg) {
            if ((this.EliminarCarpetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCarpetaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/getInboxFolder", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carpeta getInboxFolder(Alumno a) {
            object[] results = this.Invoke("getInboxFolder", new object[] {
                        a});
            return ((Carpeta)(results[0]));
        }
        
        /// <remarks/>
        public void getInboxFolderAsync(Alumno a) {
            this.getInboxFolderAsync(a, null);
        }
        
        /// <remarks/>
        public void getInboxFolderAsync(Alumno a, object userState) {
            if ((this.getInboxFolderOperationCompleted == null)) {
                this.getInboxFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInboxFolderOperationCompleted);
            }
            this.InvokeAsync("getInboxFolder", new object[] {
                        a}, this.getInboxFolderOperationCompleted, userState);
        }
        
        private void OngetInboxFolderOperationCompleted(object arg) {
            if ((this.getInboxFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInboxFolderCompleted(this, new getInboxFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/IsCarpetaSistema", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsCarpetaSistema(Carpeta c) {
            object[] results = this.Invoke("IsCarpetaSistema", new object[] {
                        c});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsCarpetaSistemaAsync(Carpeta c) {
            this.IsCarpetaSistemaAsync(c, null);
        }
        
        /// <remarks/>
        public void IsCarpetaSistemaAsync(Carpeta c, object userState) {
            if ((this.IsCarpetaSistemaOperationCompleted == null)) {
                this.IsCarpetaSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCarpetaSistemaOperationCompleted);
            }
            this.InvokeAsync("IsCarpetaSistema", new object[] {
                        c}, this.IsCarpetaSistemaOperationCompleted, userState);
        }
        
        private void OnIsCarpetaSistemaOperationCompleted(object arg) {
            if ((this.IsCarpetaSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCarpetaSistemaCompleted(this, new IsCarpetaSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/GetCarpeta", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carpeta GetCarpeta(Carpeta c) {
            object[] results = this.Invoke("GetCarpeta", new object[] {
                        c});
            return ((Carpeta)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarpetaAsync(Carpeta c) {
            this.GetCarpetaAsync(c, null);
        }
        
        /// <remarks/>
        public void GetCarpetaAsync(Carpeta c, object userState) {
            if ((this.GetCarpetaOperationCompleted == null)) {
                this.GetCarpetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarpetaOperationCompleted);
            }
            this.InvokeAsync("GetCarpeta", new object[] {
                        c}, this.GetCarpetaOperationCompleted, userState);
        }
        
        private void OnGetCarpetaOperationCompleted(object arg) {
            if ((this.GetCarpetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarpetaCompleted(this, new GetCarpetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/AgregarEmail", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarEmail(Email newEmail, Alumno remitente, Alumno destinatario) {
            this.Invoke("AgregarEmail", new object[] {
                        newEmail,
                        remitente,
                        destinatario});
        }
        
        /// <remarks/>
        public void AgregarEmailAsync(Email newEmail, Alumno remitente, Alumno destinatario) {
            this.AgregarEmailAsync(newEmail, remitente, destinatario, null);
        }
        
        /// <remarks/>
        public void AgregarEmailAsync(Email newEmail, Alumno remitente, Alumno destinatario, object userState) {
            if ((this.AgregarEmailOperationCompleted == null)) {
                this.AgregarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarEmailOperationCompleted);
            }
            this.InvokeAsync("AgregarEmail", new object[] {
                        newEmail,
                        remitente,
                        destinatario}, this.AgregarEmailOperationCompleted, userState);
        }
        
        private void OnAgregarEmailOperationCompleted(object arg) {
            if ((this.AgregarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarEmail", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Email[] ListarEmail(Carpeta c) {
            object[] results = this.Invoke("ListarEmail", new object[] {
                        c});
            return ((Email[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmailAsync(Carpeta c) {
            this.ListarEmailAsync(c, null);
        }
        
        /// <remarks/>
        public void ListarEmailAsync(Carpeta c, object userState) {
            if ((this.ListarEmailOperationCompleted == null)) {
                this.ListarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmailOperationCompleted);
            }
            this.InvokeAsync("ListarEmail", new object[] {
                        c}, this.ListarEmailOperationCompleted, userState);
        }
        
        private void OnListarEmailOperationCompleted(object arg) {
            if ((this.ListarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmailCompleted(this, new ListarEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/GetEmail", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Email GetEmail(Email e) {
            object[] results = this.Invoke("GetEmail", new object[] {
                        e});
            return ((Email)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailAsync(Email e) {
            this.GetEmailAsync(e, null);
        }
        
        /// <remarks/>
        public void GetEmailAsync(Email e, object userState) {
            if ((this.GetEmailOperationCompleted == null)) {
                this.GetEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailOperationCompleted);
            }
            this.InvokeAsync("GetEmail", new object[] {
                        e}, this.GetEmailOperationCompleted, userState);
        }
        
        private void OnGetEmailOperationCompleted(object arg) {
            if ((this.GetEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailCompleted(this, new GetEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/EliminarEmail", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarEmail(Email e, Carpeta carpeta) {
            this.Invoke("EliminarEmail", new object[] {
                        e,
                        carpeta});
        }
        
        /// <remarks/>
        public void EliminarEmailAsync(Email e, Carpeta carpeta) {
            this.EliminarEmailAsync(e, carpeta, null);
        }
        
        /// <remarks/>
        public void EliminarEmailAsync(Email e, Carpeta carpeta, object userState) {
            if ((this.EliminarEmailOperationCompleted == null)) {
                this.EliminarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarEmailOperationCompleted);
            }
            this.InvokeAsync("EliminarEmail", new object[] {
                        e,
                        carpeta}, this.EliminarEmailOperationCompleted, userState);
        }
        
        private void OnEliminarEmailOperationCompleted(object arg) {
            if ((this.EliminarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/MarcarEmailLeido", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarcarEmailLeido(Email e, Carpeta c) {
            this.Invoke("MarcarEmailLeido", new object[] {
                        e,
                        c});
        }
        
        /// <remarks/>
        public void MarcarEmailLeidoAsync(Email e, Carpeta c) {
            this.MarcarEmailLeidoAsync(e, c, null);
        }
        
        /// <remarks/>
        public void MarcarEmailLeidoAsync(Email e, Carpeta c, object userState) {
            if ((this.MarcarEmailLeidoOperationCompleted == null)) {
                this.MarcarEmailLeidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcarEmailLeidoOperationCompleted);
            }
            this.InvokeAsync("MarcarEmailLeido", new object[] {
                        e,
                        c}, this.MarcarEmailLeidoOperationCompleted, userState);
        }
        
        private void OnMarcarEmailLeidoOperationCompleted(object arg) {
            if ((this.MarcarEmailLeidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcarEmailLeidoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/MoverEmail", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MoverEmail(Email e, Carpeta carpetaActual, Carpeta carpetaDestino) {
            this.Invoke("MoverEmail", new object[] {
                        e,
                        carpetaActual,
                        carpetaDestino});
        }
        
        /// <remarks/>
        public void MoverEmailAsync(Email e, Carpeta carpetaActual, Carpeta carpetaDestino) {
            this.MoverEmailAsync(e, carpetaActual, carpetaDestino, null);
        }
        
        /// <remarks/>
        public void MoverEmailAsync(Email e, Carpeta carpetaActual, Carpeta carpetaDestino, object userState) {
            if ((this.MoverEmailOperationCompleted == null)) {
                this.MoverEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoverEmailOperationCompleted);
            }
            this.InvokeAsync("MoverEmail", new object[] {
                        e,
                        carpetaActual,
                        carpetaDestino}, this.MoverEmailOperationCompleted, userState);
        }
        
        private void OnMoverEmailOperationCompleted(object arg) {
            if ((this.MoverEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoverEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/getAlumno", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumno getAlumno(Alumno a) {
            object[] results = this.Invoke("getAlumno", new object[] {
                        a});
            return ((Alumno)(results[0]));
        }
        
        /// <remarks/>
        public void getAlumnoAsync(Alumno a) {
            this.getAlumnoAsync(a, null);
        }
        
        /// <remarks/>
        public void getAlumnoAsync(Alumno a, object userState) {
            if ((this.getAlumnoOperationCompleted == null)) {
                this.getAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlumnoOperationCompleted);
            }
            this.InvokeAsync("getAlumno", new object[] {
                        a}, this.getAlumnoOperationCompleted, userState);
        }
        
        private void OngetAlumnoOperationCompleted(object arg) {
            if ((this.getAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlumnoCompleted(this, new getAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/getAlumnoByCi", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumno getAlumnoByCi(int ci) {
            object[] results = this.Invoke("getAlumnoByCi", new object[] {
                        ci});
            return ((Alumno)(results[0]));
        }
        
        /// <remarks/>
        public void getAlumnoByCiAsync(int ci) {
            this.getAlumnoByCiAsync(ci, null);
        }
        
        /// <remarks/>
        public void getAlumnoByCiAsync(int ci, object userState) {
            if ((this.getAlumnoByCiOperationCompleted == null)) {
                this.getAlumnoByCiOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlumnoByCiOperationCompleted);
            }
            this.InvokeAsync("getAlumnoByCi", new object[] {
                        ci}, this.getAlumnoByCiOperationCompleted, userState);
        }
        
        private void OngetAlumnoByCiOperationCompleted(object arg) {
            if ((this.getAlumnoByCiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlumnoByCiCompleted(this, new getAlumnoByCiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/getDocente", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Docente getDocente(Docente d) {
            object[] results = this.Invoke("getDocente", new object[] {
                        d});
            return ((Docente)(results[0]));
        }
        
        /// <remarks/>
        public void getDocenteAsync(Docente d) {
            this.getDocenteAsync(d, null);
        }
        
        /// <remarks/>
        public void getDocenteAsync(Docente d, object userState) {
            if ((this.getDocenteOperationCompleted == null)) {
                this.getDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocenteOperationCompleted);
            }
            this.InvokeAsync("getDocente", new object[] {
                        d}, this.getDocenteOperationCompleted, userState);
        }
        
        private void OngetDocenteOperationCompleted(object arg) {
            if ((this.getDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocenteCompleted(this, new getDocenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/NuevoAlumno", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NuevoAlumno(Alumno a) {
            this.Invoke("NuevoAlumno", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void NuevoAlumnoAsync(Alumno a) {
            this.NuevoAlumnoAsync(a, null);
        }
        
        /// <remarks/>
        public void NuevoAlumnoAsync(Alumno a, object userState) {
            if ((this.NuevoAlumnoOperationCompleted == null)) {
                this.NuevoAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevoAlumnoOperationCompleted);
            }
            this.InvokeAsync("NuevoAlumno", new object[] {
                        a}, this.NuevoAlumnoOperationCompleted, userState);
        }
        
        private void OnNuevoAlumnoOperationCompleted(object arg) {
            if ((this.NuevoAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevoAlumnoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/NuevoDocente", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NuevoDocente(Docente d) {
            this.Invoke("NuevoDocente", new object[] {
                        d});
        }
        
        /// <remarks/>
        public void NuevoDocenteAsync(Docente d) {
            this.NuevoDocenteAsync(d, null);
        }
        
        /// <remarks/>
        public void NuevoDocenteAsync(Docente d, object userState) {
            if ((this.NuevoDocenteOperationCompleted == null)) {
                this.NuevoDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevoDocenteOperationCompleted);
            }
            this.InvokeAsync("NuevoDocente", new object[] {
                        d}, this.NuevoDocenteOperationCompleted, userState);
        }
        
        private void OnNuevoDocenteOperationCompleted(object arg) {
            if ((this.NuevoDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevoDocenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/getLoginUsuario", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario getLoginUsuario(string userName, string pass) {
            object[] results = this.Invoke("getLoginUsuario", new object[] {
                        userName,
                        pass});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void getLoginUsuarioAsync(string userName, string pass) {
            this.getLoginUsuarioAsync(userName, pass, null);
        }
        
        /// <remarks/>
        public void getLoginUsuarioAsync(string userName, string pass, object userState) {
            if ((this.getLoginUsuarioOperationCompleted == null)) {
                this.getLoginUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLoginUsuarioOperationCompleted);
            }
            this.InvokeAsync("getLoginUsuario", new object[] {
                        userName,
                        pass}, this.getLoginUsuarioOperationCompleted, userState);
        }
        
        private void OngetLoginUsuarioOperationCompleted(object arg) {
            if ((this.getLoginUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLoginUsuarioCompleted(this, new getLoginUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarAlumnosSinMovimientos", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumno[] ListarAlumnosSinMovimientos(int NumeroDias) {
            object[] results = this.Invoke("ListarAlumnosSinMovimientos", new object[] {
                        NumeroDias});
            return ((Alumno[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAlumnosSinMovimientosAsync(int NumeroDias) {
            this.ListarAlumnosSinMovimientosAsync(NumeroDias, null);
        }
        
        /// <remarks/>
        public void ListarAlumnosSinMovimientosAsync(int NumeroDias, object userState) {
            if ((this.ListarAlumnosSinMovimientosOperationCompleted == null)) {
                this.ListarAlumnosSinMovimientosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAlumnosSinMovimientosOperationCompleted);
            }
            this.InvokeAsync("ListarAlumnosSinMovimientos", new object[] {
                        NumeroDias}, this.ListarAlumnosSinMovimientosOperationCompleted, userState);
        }
        
        private void OnListarAlumnosSinMovimientosOperationCompleted(object arg) {
            if ((this.ListarAlumnosSinMovimientosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAlumnosSinMovimientosCompleted(this, new ListarAlumnosSinMovimientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarDocentes", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Docente[] ListarDocentes() {
            object[] results = this.Invoke("ListarDocentes", new object[0]);
            return ((Docente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDocentesAsync() {
            this.ListarDocentesAsync(null);
        }
        
        /// <remarks/>
        public void ListarDocentesAsync(object userState) {
            if ((this.ListarDocentesOperationCompleted == null)) {
                this.ListarDocentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDocentesOperationCompleted);
            }
            this.InvokeAsync("ListarDocentes", new object[0], this.ListarDocentesOperationCompleted, userState);
        }
        
        private void OnListarDocentesOperationCompleted(object arg) {
            if ((this.ListarDocentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDocentesCompleted(this, new ListarDocentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarAlumnos", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumno[] ListarAlumnos() {
            object[] results = this.Invoke("ListarAlumnos", new object[0]);
            return ((Alumno[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAlumnosAsync() {
            this.ListarAlumnosAsync(null);
        }
        
        /// <remarks/>
        public void ListarAlumnosAsync(object userState) {
            if ((this.ListarAlumnosOperationCompleted == null)) {
                this.ListarAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAlumnosOperationCompleted);
            }
            this.InvokeAsync("ListarAlumnos", new object[0], this.ListarAlumnosOperationCompleted, userState);
        }
        
        private void OnListarAlumnosOperationCompleted(object arg) {
            if ((this.ListarAlumnosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAlumnosCompleted(this, new ListarAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ListarAlumnosXml", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarAlumnosXml() {
            object[] results = this.Invoke("ListarAlumnosXml", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarAlumnosXmlAsync() {
            this.ListarAlumnosXmlAsync(null);
        }
        
        /// <remarks/>
        public void ListarAlumnosXmlAsync(object userState) {
            if ((this.ListarAlumnosXmlOperationCompleted == null)) {
                this.ListarAlumnosXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAlumnosXmlOperationCompleted);
            }
            this.InvokeAsync("ListarAlumnosXml", new object[0], this.ListarAlumnosXmlOperationCompleted, userState);
        }
        
        private void OnListarAlumnosXmlOperationCompleted(object arg) {
            if ((this.ListarAlumnosXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAlumnosXmlCompleted(this, new ListarAlumnosXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ActualizarStatusAlumno", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarStatusAlumno(Alumno a, bool setActiveStatus) {
            this.Invoke("ActualizarStatusAlumno", new object[] {
                        a,
                        setActiveStatus});
        }
        
        /// <remarks/>
        public void ActualizarStatusAlumnoAsync(Alumno a, bool setActiveStatus) {
            this.ActualizarStatusAlumnoAsync(a, setActiveStatus, null);
        }
        
        /// <remarks/>
        public void ActualizarStatusAlumnoAsync(Alumno a, bool setActiveStatus, object userState) {
            if ((this.ActualizarStatusAlumnoOperationCompleted == null)) {
                this.ActualizarStatusAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarStatusAlumnoOperationCompleted);
            }
            this.InvokeAsync("ActualizarStatusAlumno", new object[] {
                        a,
                        setActiveStatus}, this.ActualizarStatusAlumnoOperationCompleted, userState);
        }
        
        private void OnActualizarStatusAlumnoOperationCompleted(object arg) {
            if ((this.ActualizarStatusAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarStatusAlumnoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ModificarAlumno", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarAlumno(Alumno a) {
            this.Invoke("ModificarAlumno", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void ModificarAlumnoAsync(Alumno a) {
            this.ModificarAlumnoAsync(a, null);
        }
        
        /// <remarks/>
        public void ModificarAlumnoAsync(Alumno a, object userState) {
            if ((this.ModificarAlumnoOperationCompleted == null)) {
                this.ModificarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarAlumnoOperationCompleted);
            }
            this.InvokeAsync("ModificarAlumno", new object[] {
                        a}, this.ModificarAlumnoOperationCompleted, userState);
        }
        
        private void OnModificarAlumnoOperationCompleted(object arg) {
            if ((this.ModificarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarAlumnoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebMailWS/ModificarDocente", RequestNamespace="http://WebMailWS/", ResponseNamespace="http://WebMailWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarDocente(Docente d) {
            this.Invoke("ModificarDocente", new object[] {
                        d});
        }
        
        /// <remarks/>
        public void ModificarDocenteAsync(Docente d) {
            this.ModificarDocenteAsync(d, null);
        }
        
        /// <remarks/>
        public void ModificarDocenteAsync(Docente d, object userState) {
            if ((this.ModificarDocenteOperationCompleted == null)) {
                this.ModificarDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarDocenteOperationCompleted);
            }
            this.InvokeAsync("ModificarDocente", new object[] {
                        d}, this.ModificarDocenteOperationCompleted, userState);
        }
        
        private void OnModificarDocenteOperationCompleted(object arg) {
            if ((this.ModificarDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarDocenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebMailWS/")]
    public partial class Carpeta {
        
        private Alumno uSUARIOField;
        
        private int nUMERO_CARPETAField;
        
        private string nOMBRE_CARPETAField;
        
        private int tOTAL_EMAILSField;
        
        private int tOTAL_EMAILS_NOLEIDOSField;
        
        private Email[] lISTA_EMAILField;
        
        /// <comentarios/>
        public Alumno USUARIO {
            get {
                return this.uSUARIOField;
            }
            set {
                this.uSUARIOField = value;
            }
        }
        
        /// <comentarios/>
        public int NUMERO_CARPETA {
            get {
                return this.nUMERO_CARPETAField;
            }
            set {
                this.nUMERO_CARPETAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE_CARPETA {
            get {
                return this.nOMBRE_CARPETAField;
            }
            set {
                this.nOMBRE_CARPETAField = value;
            }
        }
        
        /// <comentarios/>
        public int TOTAL_EMAILS {
            get {
                return this.tOTAL_EMAILSField;
            }
            set {
                this.tOTAL_EMAILSField = value;
            }
        }
        
        /// <comentarios/>
        public int TOTAL_EMAILS_NOLEIDOS {
            get {
                return this.tOTAL_EMAILS_NOLEIDOSField;
            }
            set {
                this.tOTAL_EMAILS_NOLEIDOSField = value;
            }
        }
        
        /// <comentarios/>
        public Email[] LISTA_EMAIL {
            get {
                return this.lISTA_EMAILField;
            }
            set {
                this.lISTA_EMAILField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebMailWS/")]
    public partial class Alumno : Usuario {
        
        private Carpeta[] lISTA_CARPETASField;
        
        private string fOTOField;
        
        private bool aCTIVOField;
        
        private int cANTIDADENVIADOSField;
        
        private int cANTIDADRECIBIDOSField;
        
        /// <comentarios/>
        public Carpeta[] LISTA_CARPETAS {
            get {
                return this.lISTA_CARPETASField;
            }
            set {
                this.lISTA_CARPETASField = value;
            }
        }
        
        /// <comentarios/>
        public string FOTO {
            get {
                return this.fOTOField;
            }
            set {
                this.fOTOField = value;
            }
        }
        
        /// <comentarios/>
        public bool ACTIVO {
            get {
                return this.aCTIVOField;
            }
            set {
                this.aCTIVOField = value;
            }
        }
        
        /// <comentarios/>
        public int CANTIDADENVIADOS {
            get {
                return this.cANTIDADENVIADOSField;
            }
            set {
                this.cANTIDADENVIADOSField = value;
            }
        }
        
        /// <comentarios/>
        public int CANTIDADRECIBIDOS {
            get {
                return this.cANTIDADRECIBIDOSField;
            }
            set {
                this.cANTIDADRECIBIDOSField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Docente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebMailWS/")]
    public partial class Usuario {
        
        private int ciField;
        
        private string nOMBRE_USUARIOField;
        
        private string nOMBREField;
        
        private string aPELLIDOField;
        
        private string pASSField;
        
        /// <comentarios/>
        public int CI {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE_USUARIO {
            get {
                return this.nOMBRE_USUARIOField;
            }
            set {
                this.nOMBRE_USUARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string APELLIDO {
            get {
                return this.aPELLIDOField;
            }
            set {
                this.aPELLIDOField = value;
            }
        }
        
        /// <comentarios/>
        public string PASS {
            get {
                return this.pASSField;
            }
            set {
                this.pASSField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebMailWS/")]
    public partial class Email {
        
        private int nUMERO_EMAILField;
        
        private Carpeta cARPETA_REMITENTEField;
        
        private Carpeta cARPETA_DESTINATARIOField;
        
        private string cUERPOField;
        
        private string aSUNTOField;
        
        private bool lEIDOField;
        
        private System.DateTime fECHAField;
        
        /// <comentarios/>
        public int NUMERO_EMAIL {
            get {
                return this.nUMERO_EMAILField;
            }
            set {
                this.nUMERO_EMAILField = value;
            }
        }
        
        /// <comentarios/>
        public Carpeta CARPETA_REMITENTE {
            get {
                return this.cARPETA_REMITENTEField;
            }
            set {
                this.cARPETA_REMITENTEField = value;
            }
        }
        
        /// <comentarios/>
        public Carpeta CARPETA_DESTINATARIO {
            get {
                return this.cARPETA_DESTINATARIOField;
            }
            set {
                this.cARPETA_DESTINATARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string CUERPO {
            get {
                return this.cUERPOField;
            }
            set {
                this.cUERPOField = value;
            }
        }
        
        /// <comentarios/>
        public string ASUNTO {
            get {
                return this.aSUNTOField;
            }
            set {
                this.aSUNTOField = value;
            }
        }
        
        /// <comentarios/>
        public bool LEIDO {
            get {
                return this.lEIDOField;
            }
            set {
                this.lEIDOField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebMailWS/")]
    public partial class Docente : Usuario {
        
        private string[] mATERIASField;
        
        /// <comentarios/>
        public string[] MATERIAS {
            get {
                return this.mATERIASField;
            }
            set {
                this.mATERIASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AgregarCarpetaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarCarpetasCompletedEventHandler(object sender, ListarCarpetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCarpetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCarpetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carpeta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carpeta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EliminarCarpetaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getInboxFolderCompletedEventHandler(object sender, getInboxFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInboxFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInboxFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carpeta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carpeta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void IsCarpetaSistemaCompletedEventHandler(object sender, IsCarpetaSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCarpetaSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCarpetaSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCarpetaCompletedEventHandler(object sender, GetCarpetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarpetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarpetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carpeta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carpeta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AgregarEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarEmailCompletedEventHandler(object sender, ListarEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Email[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Email[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEmailCompletedEventHandler(object sender, GetEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Email Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Email)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EliminarEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MarcarEmailLeidoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MoverEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAlumnoCompletedEventHandler(object sender, getAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAlumnoByCiCompletedEventHandler(object sender, getAlumnoByCiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlumnoByCiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlumnoByCiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getDocenteCompletedEventHandler(object sender, getDocenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Docente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Docente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NuevoAlumnoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NuevoDocenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLoginUsuarioCompletedEventHandler(object sender, getLoginUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLoginUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLoginUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarAlumnosSinMovimientosCompletedEventHandler(object sender, ListarAlumnosSinMovimientosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAlumnosSinMovimientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAlumnosSinMovimientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumno[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarDocentesCompletedEventHandler(object sender, ListarDocentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDocentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDocentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Docente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Docente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarAlumnosCompletedEventHandler(object sender, ListarAlumnosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumno[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListarAlumnosXmlCompletedEventHandler(object sender, ListarAlumnosXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAlumnosXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAlumnosXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ActualizarStatusAlumnoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ModificarAlumnoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ModificarDocenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591